new_local_repository(
    name = "local_py3",
    path = "c:/python37",
    build_file_content = """
cc_library(
    name = "py3",
    hdrs = glob(["include/*.h"]),
    deps = [":python37_lib"],
    visibility = ["//visibility:public"],
    strip_include_prefix = "include/",
)

cc_import(
    name = "python37_lib",
    static_library = "Libs/python37.lib",
)
""",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

maybe(
    http_archive,
    name = "bazel_skylib",
    url = "https://github.com/bazelbuild/bazel-skylib/releases/download/0.9.0/bazel_skylib-0.9.0.tar.gz",
    sha256 = "1dde365491125a3db70731e25658dfdd3bc5dbdfd11b840b3e987ecf043c7ca0",
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")
bazel_skylib_workspace()
