load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "85ffff62a4c22a74dbd98d05da6cf40f497344b3dbf1e1ab0a37ab2a1a6ca014",
    strip_prefix = "rules_docker-0.23.0",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.23.0/rules_docker-v0.23.0.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)

container_pull(
    name = "java_base",
    registry = "gcr.io",
    repository = "distroless/java",
    tag = "latest",
)

# flaky, possibly due to docker.io rate limit
container_pull(
    name = "debian",
    registry = "docker.io",
    repository = "debian",
    tag = "latest",
)

container_pull(
    name = "debian-gcr",
    registry = "marketplace.gcr.io",
    repository = "google/debian11",
    tag = "latest",
)
